//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDateTime", Namespace="http://tempuri.org/", ItemName="dateTime")]
    public class ArrayOfDateTime : System.Collections.Generic.List<System.DateTime>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    public partial class TimeSpan : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogin", ReplyAction="*")]
        ServiceReference1.GetLoginResponse GetLogin(ServiceReference1.GetLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetLoginResponse> GetLoginAsync(ServiceReference1.GetLoginRequest request);
        
        // CODEGEN: Generating message contract since element name Date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertReceipt", ReplyAction="*")]
        ServiceReference1.InsertReceiptResponse InsertReceipt(ServiceReference1.InsertReceiptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.InsertReceiptResponse> InsertReceiptAsync(ServiceReference1.InsertReceiptRequest request);
        
        // CODEGEN: Generating message contract since element name Branch_Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRecord", ReplyAction="*")]
        ServiceReference1.InsertRecordResponse InsertRecord(ServiceReference1.InsertRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.InsertRecordResponse> InsertRecordAsync(ServiceReference1.InsertRecordRequest request);
        
        // CODEGEN: Generating message contract since element name ItemList from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemName", ReplyAction="*")]
        ServiceReference1.GetItemNameResponse GetItemName(ServiceReference1.GetItemNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetItemNameResponse> GetItemNameAsync(ServiceReference1.GetItemNameRequest request);
        
        // CODEGEN: Generating message contract since element name BranchName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchName", ReplyAction="*")]
        ServiceReference1.GetBranchNameResponse GetBranchName(ServiceReference1.GetBranchNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetBranchNameResponse> GetBranchNameAsync(ServiceReference1.GetBranchNameRequest request);
        
        // CODEGEN: Generating message contract since element name Item_Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateItem", ReplyAction="*")]
        ServiceReference1.UpdateItemResponse UpdateItem(ServiceReference1.UpdateItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.UpdateItemResponse> UpdateItemAsync(ServiceReference1.UpdateItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        ServiceReference1.GetItemResponse GetItem(ServiceReference1.GetItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetItemResponse> GetItemAsync(ServiceReference1.GetItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReceipt", ReplyAction="*")]
        ServiceReference1.GetReceiptResponse GetReceipt(ServiceReference1.GetReceiptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetReceiptResponse> GetReceiptAsync(ServiceReference1.GetReceiptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGraphRecords", ReplyAction="*")]
        ServiceReference1.GetGraphRecordsResponse GetGraphRecords(ServiceReference1.GetGraphRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGraphRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetGraphRecordsResponse> GetGraphRecordsAsync(ServiceReference1.GetGraphRecordsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogin", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetLoginRequestBody Body;
        
        public GetLoginRequest()
        {
        }
        
        public GetLoginRequest(ServiceReference1.GetLoginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        public GetLoginRequestBody()
        {
        }
        
        public GetLoginRequestBody(string Username)
        {
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetLoginResponseBody Body;
        
        public GetLoginResponse()
        {
        }
        
        public GetLoginResponse(ServiceReference1.GetLoginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username_Out;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Account_Type;
        
        public GetLoginResponseBody()
        {
        }
        
        public GetLoginResponseBody(string Username_Out, string Password, string Account_Type)
        {
            this.Username_Out = Username_Out;
            this.Password = Password;
            this.Account_Type = Account_Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertReceiptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertReceipt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.InsertReceiptRequestBody Body;
        
        public InsertReceiptRequest()
        {
        }
        
        public InsertReceiptRequest(ServiceReference1.InsertReceiptRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertReceiptRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Time;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Item_Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Transaction_Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Change;
        
        public InsertReceiptRequestBody()
        {
        }
        
        public InsertReceiptRequestBody(string Date, string Time, int Item_Amount, int Transaction_Total, string Username, int Change)
        {
            this.Date = Date;
            this.Time = Time;
            this.Item_Amount = Item_Amount;
            this.Transaction_Total = Transaction_Total;
            this.Username = Username;
            this.Change = Change;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertReceiptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertReceiptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.InsertReceiptResponseBody Body;
        
        public InsertReceiptResponse()
        {
        }
        
        public InsertReceiptResponse(ServiceReference1.InsertReceiptResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertReceiptResponseBody
    {
        
        public InsertReceiptResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRecord", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.InsertRecordRequestBody Body;
        
        public InsertRecordRequest()
        {
        }
        
        public InsertRecordRequest(ServiceReference1.InsertRecordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRecordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Amount_Purchased;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Branch_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Item_Name;
        
        public InsertRecordRequestBody()
        {
        }
        
        public InsertRecordRequestBody(int Amount_Purchased, string Branch_Name, string Date, string Time, string Item_Name)
        {
            this.Amount_Purchased = Amount_Purchased;
            this.Branch_Name = Branch_Name;
            this.Date = Date;
            this.Time = Time;
            this.Item_Name = Item_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.InsertRecordResponseBody Body;
        
        public InsertRecordResponse()
        {
        }
        
        public InsertRecordResponse(ServiceReference1.InsertRecordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertRecordResponseBody
    {
        
        public InsertRecordResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetItemNameRequestBody Body;
        
        public GetItemNameRequest()
        {
        }
        
        public GetItemNameRequest(ServiceReference1.GetItemNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetItemNameRequestBody
    {
        
        public GetItemNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetItemNameResponseBody Body;
        
        public GetItemNameResponse()
        {
        }
        
        public GetItemNameResponse(ServiceReference1.GetItemNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString ItemList;
        
        public GetItemNameResponseBody()
        {
        }
        
        public GetItemNameResponseBody(ServiceReference1.ArrayOfString ItemList)
        {
            this.ItemList = ItemList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBranchNameRequestBody Body;
        
        public GetBranchNameRequest()
        {
        }
        
        public GetBranchNameRequest(ServiceReference1.GetBranchNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBranchNameRequestBody
    {
        
        public GetBranchNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBranchNameResponseBody Body;
        
        public GetBranchNameResponse()
        {
        }
        
        public GetBranchNameResponse(ServiceReference1.GetBranchNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBranchNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString BranchName;
        
        public GetBranchNameResponseBody()
        {
        }
        
        public GetBranchNameResponseBody(ServiceReference1.ArrayOfString BranchName)
        {
            this.BranchName = BranchName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateItem", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.UpdateItemRequestBody Body;
        
        public UpdateItemRequest()
        {
        }
        
        public UpdateItemRequest(ServiceReference1.UpdateItemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateItemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Item_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Item_Stock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Branch_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewName;
        
        public UpdateItemRequestBody()
        {
        }
        
        public UpdateItemRequestBody(string Item_Name, int Item_Stock, string Branch_Name, string NewName)
        {
            this.Item_Name = Item_Name;
            this.Item_Stock = Item_Stock;
            this.Branch_Name = Branch_Name;
            this.NewName = NewName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.UpdateItemResponseBody Body;
        
        public UpdateItemResponse()
        {
        }
        
        public UpdateItemResponse(ServiceReference1.UpdateItemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateItemResponseBody
    {
        
        public UpdateItemResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItem", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetItemRequestBody Body;
        
        public GetItemRequest()
        {
        }
        
        public GetItemRequest(ServiceReference1.GetItemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Item_Name;
        
        public GetItemRequestBody()
        {
        }
        
        public GetItemRequestBody(string Item_Name)
        {
            this.Item_Name = Item_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetItemResponseBody Body;
        
        public GetItemResponse()
        {
        }
        
        public GetItemResponse(ServiceReference1.GetItemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Item_Stock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Branch_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Item_N;
        
        public GetItemResponseBody()
        {
        }
        
        public GetItemResponseBody(string Item_Stock, string Branch_Name, string Item_N)
        {
            this.Item_Stock = Item_Stock;
            this.Branch_Name = Branch_Name;
            this.Item_N = Item_N;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceipt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetReceiptRequestBody Body;
        
        public GetReceiptRequest()
        {
        }
        
        public GetReceiptRequest(ServiceReference1.GetReceiptRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetReceiptRequestBody
    {
        
        public GetReceiptRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetReceiptResponseBody Body;
        
        public GetReceiptResponse()
        {
        }
        
        public GetReceiptResponse(ServiceReference1.GetReceiptResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReceiptResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.ArrayOfDateTime Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.TimeSpan[] Time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceReference1.ArrayOfInt AmountOfItems;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServiceReference1.ArrayOfInt TransactionTotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ServiceReference1.ArrayOfInt Change;
        
        public GetReceiptResponseBody()
        {
        }
        
        public GetReceiptResponseBody(ServiceReference1.ArrayOfString Username, ServiceReference1.ArrayOfDateTime Date, ServiceReference1.TimeSpan[] Time, ServiceReference1.ArrayOfInt AmountOfItems, ServiceReference1.ArrayOfInt TransactionTotal, ServiceReference1.ArrayOfInt Change)
        {
            this.Username = Username;
            this.Date = Date;
            this.Time = Time;
            this.AmountOfItems = AmountOfItems;
            this.TransactionTotal = TransactionTotal;
            this.Change = Change;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGraphRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGraphRecords", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetGraphRecordsRequestBody Body;
        
        public GetGraphRecordsRequest()
        {
        }
        
        public GetGraphRecordsRequest(ServiceReference1.GetGraphRecordsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGraphRecordsRequestBody
    {
        
        public GetGraphRecordsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGraphRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGraphRecordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetGraphRecordsResponseBody Body;
        
        public GetGraphRecordsResponse()
        {
        }
        
        public GetGraphRecordsResponse(ServiceReference1.GetGraphRecordsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGraphRecordsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString Item_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.ArrayOfString Branch_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.ArrayOfInt Amount_Purchased;
        
        public GetGraphRecordsResponseBody()
        {
        }
        
        public GetGraphRecordsResponseBody(ServiceReference1.ArrayOfString Item_Name, ServiceReference1.ArrayOfString Branch_Name, ServiceReference1.ArrayOfInt Amount_Purchased)
        {
            this.Item_Name = Item_Name;
            this.Branch_Name = Branch_Name;
            this.Amount_Purchased = Amount_Purchased;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebServiceSoapChannel : ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebServiceSoap>, ServiceReference1.WebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetLoginResponse ServiceReference1.WebServiceSoap.GetLogin(ServiceReference1.GetLoginRequest request)
        {
            return base.Channel.GetLogin(request);
        }
        
        public string GetLogin(string Username, out string Password, out string Account_Type)
        {
            ServiceReference1.GetLoginRequest inValue = new ServiceReference1.GetLoginRequest();
            inValue.Body = new ServiceReference1.GetLoginRequestBody();
            inValue.Body.Username = Username;
            ServiceReference1.GetLoginResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetLogin(inValue);
            Password = retVal.Body.Password;
            Account_Type = retVal.Body.Account_Type;
            return retVal.Body.Username_Out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetLoginResponse> ServiceReference1.WebServiceSoap.GetLoginAsync(ServiceReference1.GetLoginRequest request)
        {
            return base.Channel.GetLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLoginResponse> GetLoginAsync(string Username)
        {
            ServiceReference1.GetLoginRequest inValue = new ServiceReference1.GetLoginRequest();
            inValue.Body = new ServiceReference1.GetLoginRequestBody();
            inValue.Body.Username = Username;
            return ((ServiceReference1.WebServiceSoap)(this)).GetLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.InsertReceiptResponse ServiceReference1.WebServiceSoap.InsertReceipt(ServiceReference1.InsertReceiptRequest request)
        {
            return base.Channel.InsertReceipt(request);
        }
        
        public void InsertReceipt(string Date, string Time, int Item_Amount, int Transaction_Total, string Username, int Change)
        {
            ServiceReference1.InsertReceiptRequest inValue = new ServiceReference1.InsertReceiptRequest();
            inValue.Body = new ServiceReference1.InsertReceiptRequestBody();
            inValue.Body.Date = Date;
            inValue.Body.Time = Time;
            inValue.Body.Item_Amount = Item_Amount;
            inValue.Body.Transaction_Total = Transaction_Total;
            inValue.Body.Username = Username;
            inValue.Body.Change = Change;
            ServiceReference1.InsertReceiptResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).InsertReceipt(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InsertReceiptResponse> ServiceReference1.WebServiceSoap.InsertReceiptAsync(ServiceReference1.InsertReceiptRequest request)
        {
            return base.Channel.InsertReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InsertReceiptResponse> InsertReceiptAsync(string Date, string Time, int Item_Amount, int Transaction_Total, string Username, int Change)
        {
            ServiceReference1.InsertReceiptRequest inValue = new ServiceReference1.InsertReceiptRequest();
            inValue.Body = new ServiceReference1.InsertReceiptRequestBody();
            inValue.Body.Date = Date;
            inValue.Body.Time = Time;
            inValue.Body.Item_Amount = Item_Amount;
            inValue.Body.Transaction_Total = Transaction_Total;
            inValue.Body.Username = Username;
            inValue.Body.Change = Change;
            return ((ServiceReference1.WebServiceSoap)(this)).InsertReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.InsertRecordResponse ServiceReference1.WebServiceSoap.InsertRecord(ServiceReference1.InsertRecordRequest request)
        {
            return base.Channel.InsertRecord(request);
        }
        
        public void InsertRecord(int Amount_Purchased, string Branch_Name, string Date, string Time, string Item_Name)
        {
            ServiceReference1.InsertRecordRequest inValue = new ServiceReference1.InsertRecordRequest();
            inValue.Body = new ServiceReference1.InsertRecordRequestBody();
            inValue.Body.Amount_Purchased = Amount_Purchased;
            inValue.Body.Branch_Name = Branch_Name;
            inValue.Body.Date = Date;
            inValue.Body.Time = Time;
            inValue.Body.Item_Name = Item_Name;
            ServiceReference1.InsertRecordResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).InsertRecord(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InsertRecordResponse> ServiceReference1.WebServiceSoap.InsertRecordAsync(ServiceReference1.InsertRecordRequest request)
        {
            return base.Channel.InsertRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InsertRecordResponse> InsertRecordAsync(int Amount_Purchased, string Branch_Name, string Date, string Time, string Item_Name)
        {
            ServiceReference1.InsertRecordRequest inValue = new ServiceReference1.InsertRecordRequest();
            inValue.Body = new ServiceReference1.InsertRecordRequestBody();
            inValue.Body.Amount_Purchased = Amount_Purchased;
            inValue.Body.Branch_Name = Branch_Name;
            inValue.Body.Date = Date;
            inValue.Body.Time = Time;
            inValue.Body.Item_Name = Item_Name;
            return ((ServiceReference1.WebServiceSoap)(this)).InsertRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetItemNameResponse ServiceReference1.WebServiceSoap.GetItemName(ServiceReference1.GetItemNameRequest request)
        {
            return base.Channel.GetItemName(request);
        }
        
        public ServiceReference1.ArrayOfString GetItemName()
        {
            ServiceReference1.GetItemNameRequest inValue = new ServiceReference1.GetItemNameRequest();
            inValue.Body = new ServiceReference1.GetItemNameRequestBody();
            ServiceReference1.GetItemNameResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetItemName(inValue);
            return retVal.Body.ItemList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetItemNameResponse> ServiceReference1.WebServiceSoap.GetItemNameAsync(ServiceReference1.GetItemNameRequest request)
        {
            return base.Channel.GetItemNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetItemNameResponse> GetItemNameAsync()
        {
            ServiceReference1.GetItemNameRequest inValue = new ServiceReference1.GetItemNameRequest();
            inValue.Body = new ServiceReference1.GetItemNameRequestBody();
            return ((ServiceReference1.WebServiceSoap)(this)).GetItemNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetBranchNameResponse ServiceReference1.WebServiceSoap.GetBranchName(ServiceReference1.GetBranchNameRequest request)
        {
            return base.Channel.GetBranchName(request);
        }
        
        public ServiceReference1.ArrayOfString GetBranchName()
        {
            ServiceReference1.GetBranchNameRequest inValue = new ServiceReference1.GetBranchNameRequest();
            inValue.Body = new ServiceReference1.GetBranchNameRequestBody();
            ServiceReference1.GetBranchNameResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetBranchName(inValue);
            return retVal.Body.BranchName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetBranchNameResponse> ServiceReference1.WebServiceSoap.GetBranchNameAsync(ServiceReference1.GetBranchNameRequest request)
        {
            return base.Channel.GetBranchNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBranchNameResponse> GetBranchNameAsync()
        {
            ServiceReference1.GetBranchNameRequest inValue = new ServiceReference1.GetBranchNameRequest();
            inValue.Body = new ServiceReference1.GetBranchNameRequestBody();
            return ((ServiceReference1.WebServiceSoap)(this)).GetBranchNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.UpdateItemResponse ServiceReference1.WebServiceSoap.UpdateItem(ServiceReference1.UpdateItemRequest request)
        {
            return base.Channel.UpdateItem(request);
        }
        
        public void UpdateItem(string Item_Name, int Item_Stock, string Branch_Name, string NewName)
        {
            ServiceReference1.UpdateItemRequest inValue = new ServiceReference1.UpdateItemRequest();
            inValue.Body = new ServiceReference1.UpdateItemRequestBody();
            inValue.Body.Item_Name = Item_Name;
            inValue.Body.Item_Stock = Item_Stock;
            inValue.Body.Branch_Name = Branch_Name;
            inValue.Body.NewName = NewName;
            ServiceReference1.UpdateItemResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).UpdateItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateItemResponse> ServiceReference1.WebServiceSoap.UpdateItemAsync(ServiceReference1.UpdateItemRequest request)
        {
            return base.Channel.UpdateItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateItemResponse> UpdateItemAsync(string Item_Name, int Item_Stock, string Branch_Name, string NewName)
        {
            ServiceReference1.UpdateItemRequest inValue = new ServiceReference1.UpdateItemRequest();
            inValue.Body = new ServiceReference1.UpdateItemRequestBody();
            inValue.Body.Item_Name = Item_Name;
            inValue.Body.Item_Stock = Item_Stock;
            inValue.Body.Branch_Name = Branch_Name;
            inValue.Body.NewName = NewName;
            return ((ServiceReference1.WebServiceSoap)(this)).UpdateItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetItemResponse ServiceReference1.WebServiceSoap.GetItem(ServiceReference1.GetItemRequest request)
        {
            return base.Channel.GetItem(request);
        }
        
        public string GetItem(string Item_Name, out string Branch_Name, out string Item_N)
        {
            ServiceReference1.GetItemRequest inValue = new ServiceReference1.GetItemRequest();
            inValue.Body = new ServiceReference1.GetItemRequestBody();
            inValue.Body.Item_Name = Item_Name;
            ServiceReference1.GetItemResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetItem(inValue);
            Branch_Name = retVal.Body.Branch_Name;
            Item_N = retVal.Body.Item_N;
            return retVal.Body.Item_Stock;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetItemResponse> ServiceReference1.WebServiceSoap.GetItemAsync(ServiceReference1.GetItemRequest request)
        {
            return base.Channel.GetItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetItemResponse> GetItemAsync(string Item_Name)
        {
            ServiceReference1.GetItemRequest inValue = new ServiceReference1.GetItemRequest();
            inValue.Body = new ServiceReference1.GetItemRequestBody();
            inValue.Body.Item_Name = Item_Name;
            return ((ServiceReference1.WebServiceSoap)(this)).GetItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetReceiptResponse ServiceReference1.WebServiceSoap.GetReceipt(ServiceReference1.GetReceiptRequest request)
        {
            return base.Channel.GetReceipt(request);
        }
        
        public ServiceReference1.ArrayOfString GetReceipt(out ServiceReference1.ArrayOfDateTime Date, out ServiceReference1.TimeSpan[] Time, out ServiceReference1.ArrayOfInt AmountOfItems, out ServiceReference1.ArrayOfInt TransactionTotal, out ServiceReference1.ArrayOfInt Change)
        {
            ServiceReference1.GetReceiptRequest inValue = new ServiceReference1.GetReceiptRequest();
            inValue.Body = new ServiceReference1.GetReceiptRequestBody();
            ServiceReference1.GetReceiptResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetReceipt(inValue);
            Date = retVal.Body.Date;
            Time = retVal.Body.Time;
            AmountOfItems = retVal.Body.AmountOfItems;
            TransactionTotal = retVal.Body.TransactionTotal;
            Change = retVal.Body.Change;
            return retVal.Body.Username;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetReceiptResponse> ServiceReference1.WebServiceSoap.GetReceiptAsync(ServiceReference1.GetReceiptRequest request)
        {
            return base.Channel.GetReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetReceiptResponse> GetReceiptAsync()
        {
            ServiceReference1.GetReceiptRequest inValue = new ServiceReference1.GetReceiptRequest();
            inValue.Body = new ServiceReference1.GetReceiptRequestBody();
            return ((ServiceReference1.WebServiceSoap)(this)).GetReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetGraphRecordsResponse ServiceReference1.WebServiceSoap.GetGraphRecords(ServiceReference1.GetGraphRecordsRequest request)
        {
            return base.Channel.GetGraphRecords(request);
        }
        
        public ServiceReference1.ArrayOfString GetGraphRecords(out ServiceReference1.ArrayOfString Branch_Name, out ServiceReference1.ArrayOfInt Amount_Purchased)
        {
            ServiceReference1.GetGraphRecordsRequest inValue = new ServiceReference1.GetGraphRecordsRequest();
            inValue.Body = new ServiceReference1.GetGraphRecordsRequestBody();
            ServiceReference1.GetGraphRecordsResponse retVal = ((ServiceReference1.WebServiceSoap)(this)).GetGraphRecords(inValue);
            Branch_Name = retVal.Body.Branch_Name;
            Amount_Purchased = retVal.Body.Amount_Purchased;
            return retVal.Body.Item_Name;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetGraphRecordsResponse> ServiceReference1.WebServiceSoap.GetGraphRecordsAsync(ServiceReference1.GetGraphRecordsRequest request)
        {
            return base.Channel.GetGraphRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetGraphRecordsResponse> GetGraphRecordsAsync()
        {
            ServiceReference1.GetGraphRecordsRequest inValue = new ServiceReference1.GetGraphRecordsRequest();
            inValue.Body = new ServiceReference1.GetGraphRecordsRequestBody();
            return ((ServiceReference1.WebServiceSoap)(this)).GetGraphRecordsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.41:45455//WebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.41:45455//WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
            
            WebServiceSoap12,
        }
    }
}
